# Generated by Django 5.1.2 on 2025-03-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('film', 'Film'), ('music', 'Müzik'), ('series', 'Dizi'), ('anime', 'Anime'), ('documentary', 'Belgesel')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('source_url', models.URLField()),
            ],
        ),
    ]
